name: Flutter Android Nightly Build

on:
  #schedule:
    # schedule build every night
    #- cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-android-nightly-build:
    uses: ./.github/workflows/flutter-build_android.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
