name: Flutter Windows Nightly Build

on:
  #schedule:
    # schedule build every night
    #- cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-windows-nightly-build:
    uses: ./.github/workflows/flutter-build_windows.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "windows-nightly"
